@entryAgicapUniqueId = {{$guid}}

### Generates a new access token.
# @name auth
POST {{baseUrl}}/auth/v1/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded

client_id={{$processEnv %clientId}}
&client_secret={{$processEnv %clientSecret}}
&grant_type=client_credentials
&scope=agicap:public-api

### Fetches the entries of the purchase journal.
GET {{baseUrl}}/purchase-journal/v1/entities/{{$processEnv %entity}}/accounting-purchases?LastSynchronizationDate=2026-01-01T00:00:00Z&PageSize=100
Accept: application/json
Authorization: Bearer {{auth.response.body.access_token}}

### Notifies Agicap that the specified purchase journal entries were not correctly imported in the client accounting system.
POST {{baseUrl}}/purchase-journal/v1/entities/{{$processEnv %entity}}/accounting-purchases/exported/mark-as-not-imported
Accept: application/json
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
	"entriesNotImported": [
		{
			"entryAgicapUniqueId": "{{entryAgicapUniqueId}}",
			"errors": [
				{"errorMessage": "I'm testing out the Public API.", "errorType": "OTHER"}
			]
		}
	]
}
