<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>MC2IT</Company>
		<Copyright>© MC2IT</Copyright>
		<Description>An Agicap API client library for PowerShell.</Description>
		<Product>Agicap for PowerShell</Product>
		<Version>0.5.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Mc2it.Agicap.PowerShell</AssemblyName>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutDir>../Binaries</OutDir>
		<RootNamespace>Mc2it.Agicap</RootNamespace>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mc2it.Agicap" Version="0.*" />
		<!-- TODO <ProjectReference Include="../../../net/Agicap/Sources/Agicap.csproj" /> -->
	</ItemGroup>
</Project>
