<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Company>MC2IT</Company>
		<Copyright>© MC2IT</Copyright>
		<Description>TODO</Description>
		<Product>Agicap SDK PowerShell</Product>
		<Version>0.2.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>Mc2it.Agicap</AssemblyName>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutDir>../Binaries</OutDir>
		<RootNamespace>Mc2it.Agicap</RootNamespace>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.PowerShell.Commands.Utility" Version="7.6.*" PrivateAssets="all" />
		<PackageReference Include="System.Management.Automation" Version="7.6.*" PrivateAssets="all" />
		<Using Include="System.Management.Automation" />
	</ItemGroup>
</Project>
