namespace Mc2it.Agicap;

/// <summary>
/// A machine-readable format for specifying errors in HTTP API responses based on RFC 7807.
/// </summary>
public sealed class ProblemDetails {

	/// <summary>
	/// A human-readable explanation specific to this occurrence of the problem.
	/// </summary>
	public string Detail { get; init; } = "";

	/// <summary>
	/// The extension members.
	/// </summary>
	public IDictionary<string, object?> Extensions { get; init; } = new Dictionary<string, object?>();

	/// <summary>
	/// A URI reference that identifies the specific occurrence of the problem.
	/// </summary>
	public string Instance { get; init; } = "";

	/// <summary>
	/// The HTTP status code generated by the origin server for this occurrence of the problem.
	/// </summary>
	public int Status { get; init; } = 400;

	/// <summary>
	/// A short, human-readable summary of the problem type.
	/// </summary>
	public string Title { get; init; } = "";

	/// <summary>
	/// A URI reference that identifies the problem type.
	/// </summary>
	public string Type { get; init; } = "";

	/// <summary>
	/// Creates new problem details from the specified JSON entity.
	/// </summary>
	/// <param name="psObject">The JSON entity.</param>
	/// <returns>The problem details corresponding to the specified JSON entity.</returns>
	public static explicit operator ProblemDetails(PSObject psObject) {
		var exclusions = new[] { "detail", "instance", "status", "title", "type" };
		var extensions = psObject.Properties
			.Where(property => !exclusions.Contains(property.Name))
			.ToDictionary(property => property.Name, property => (object?) property.Value);

		var json = (dynamic) psObject;
		return new ProblemDetails() {
			Detail = json.detail is string detail ? detail : "",
			Extensions = extensions,
			Instance = json.instance is string instance ? instance : "",
			Status = json.status is int status ? status : 400,
			Title = json.title is string title ? title : "",
			Type = json.type is string type ? type : ""
		};
	}
}
