namespace Mc2it.Agicap;

/// <summary>
/// A machine-readable format for specifying errors in HTTP API responses based on RFC 7807.
/// </summary>
public sealed class ProblemDetails {

	/// <summary>
	/// The list of properties to exclude from the extension members.
	/// </summary>
	private static readonly string[] excludedProperties = ["detail", "instance", "status", "title", "type"];

	/// <summary>
	/// A human-readable explanation specific to this occurrence of the problem.
	/// </summary>
	public string Detail { get; set; } = "";

	/// <summary>
	/// The extension members.
	/// </summary>
	public IDictionary<string, object?> Extensions { get; set; } = new Dictionary<string, object?>();

	/// <summary>
	/// A URI reference that identifies the specific occurrence of the problem.
	/// </summary>
	public Uri? Instance { get; set; }

	/// <summary>
	/// The HTTP status code generated by the origin server for this occurrence of the problem.
	/// </summary>
	public int Status { get; set; } = 400;

	/// <summary>
	/// A short, human-readable summary of the problem type.
	/// </summary>
	public string Title { get; set; } = "";

	/// <summary>
	/// A URI reference that identifies the problem type.
	/// </summary>
	public Uri? Type { get; set; }

	/// <summary>
	/// Creates new problem details from the specified JSON payload.
	/// </summary>
	/// <param name="psObject">The JSON payload.</param>
	/// <returns>The problem details corresponding to the specified JSON payload.</returns>
	public static explicit operator ProblemDetails(PSObject psObject) {
		var extensions = psObject.Properties
			.Where(property => !excludedProperties.Contains(property.Name.ToLowerInvariant()))
			.ToDictionary(property => property.Name, property => (object?) property.Value);

		var json = (dynamic) psObject;
		return new() {
			Detail = Convert.ToString(json.detail) ?? "",
			Extensions = extensions,
			Instance = Convert.ToUri(json.instance),
			Status = Convert.ToInt32(json.status) ?? 400,
			Title = Convert.ToString(json.title) ?? "",
			Type = Convert.ToUri(json.type)
		};
	}
}
