namespace Mc2it.Agicap.TreasuryBankJournal;

using System.Globalization;

/// <summary>
///	Represents an entry of the Agicap treasury bank journal.
/// </summary>
public class BankJournalEntry {

	/// <summary>
	/// An optional ERP-specific external identifier for the bank accounting account.
	/// </summary>
	public string AccountingAccountExternalId { get; set; } = "";

	/// <summary>
	/// The accounting account number.
	/// </summary>
	public string AccountingAccountNumber { get; set; } = "";

	/// <summary>
	/// The accounting currency ISO code.
	/// </summary>
	public string AccountingCurrency { get; set; } = RegionInfo.CurrentRegion.ISOCurrencySymbol;

	/// <summary>
	/// A unique identifier generated by Agicap.
	/// </summary>
	public Guid AgicapUniqueId { get; set; } = Guid.Empty;

	/// <summary>
	/// The bank account name.
	/// </summary>
	public string BankAccountName { get; set; } = "";

	/// <summary>
	/// The banking transaction causale.
	/// </summary>
	public string Causale { get; set; } = "";

	/// <summary>
	/// The bank journal entry counterparts.
	/// </summary>
	public IList<Counterpart> Counterparts { get; set; } = [];

	/// <summary>
	/// The credit value in accounting currency.
	/// </summary>
	public decimal CreditInAccountingCurrency { get; set; }

	/// <summary>
	/// The credit value in original currency.
	/// </summary>
	public decimal CreditInOriginalCurrency { get; set; }

	/// <summary>
	/// The debit value in accounting currency.
	/// </summary>
	public decimal DebitInAccountingCurrency { get; set; }

	/// <summary>
	/// The debit value in original currency.
	/// </summary>
	public decimal DebitInOriginalCurrency { get; set; }

	/// <summary>
	/// A free-text memo for the bank journal entry.
	/// </summary>
	public string EntryMemo { get; set; } = "";

	/// <summary>
	/// The exchange rate applied between the original currency amount and the accounting currency amount.
	/// </summary>
	public double ExchangeRate { get; set; }

	/// <summary>
	/// A unique reference per entity generated by Agicap, designed to match reference formats expected by accounting systems.
	/// </summary>
	public string ExportEntryReference { get; set; } = "";

	/// <summary>
	/// The index of the bank journal entry in the bank journal (starts at 1).
	/// </summary>
	public int IndexInExport { get; set; } = 1;

	/// <summary>
	/// The index of the bank journal entry in the current year (starts at 1).
	/// </summary>
	public int IndexInYear { get; set; } = 1;

	/// <summary>
	/// The journal code.
	/// </summary>
	public string JournalCode { get; set; } = "";

	/// <summary>
	/// The bank journal entry name.
	/// </summary>
	public string Name { get; set; } = "";

	/// <summary>
	/// The original currency ISO code.
	/// </summary>
	public string OriginalCurrency { get; set; } = RegionInfo.CurrentRegion.ISOCurrencySymbol;

	/// <summary>
	/// The banking transaction payment date.
	/// </summary>
	public DateTime PaymentDate { get; set; } = DateTime.MinValue;

	/// <summary>
	/// The journal entry type.
	/// </summary>
	public BankJournalEntryType Type { get; set; } = BankJournalEntryType.BANK;

	/// <summary>
	/// Creates a new counterpart from the specified JSON payload.
	/// </summary>
	/// <param name="psObject">The JSON payload.</param>
	/// <returns>The counterpart corresponding to the specified JSON payload.</returns>
	public static explicit operator BankJournalEntry(PSObject psObject) {
		var json = (dynamic) psObject;
		return new() {
			AccountingAccountExternalId = Convert.ToString(json.accountingAccountExternalId) ?? "",
			AccountingAccountNumber = Convert.ToString(json.accountingAccountNumber) ?? "",
			AccountingCurrency = Convert.ToString(json.accountingCurrency) ?? RegionInfo.CurrentRegion.ISOCurrencySymbol,
			AgicapUniqueId = Convert.ToGuid(json.agicapUniqueId) ?? Guid.Empty,
			BankAccountName = Convert.ToString(json.bankAccountName) ?? "",
			Causale = Convert.ToString(json.causale) ?? "",
			Counterparts = Convert.ToList<Counterpart>(json.counterparts),
			CreditInAccountingCurrency = Convert.ToDecimal(json.creditInAccountingCurrency) ?? 0,
			CreditInOriginalCurrency = Convert.ToDecimal(json.creditInOriginalCurrency) ?? 0,
			DebitInAccountingCurrency = Convert.ToDecimal(json.debitInAccountingCurrency) ?? 0,
			DebitInOriginalCurrency = Convert.ToDecimal(json.debitInOriginalCurrency) ?? 0,
			EntryMemo = Convert.ToString(json.entryMemo) ?? "",
			ExchangeRate = Convert.ToDouble(json.exchangeRate) ?? 0,
			ExportEntryReference = Convert.ToString(json.exportEntryReference) ?? "",
			IndexInExport = Convert.ToInt32(json.indexInExport) ?? 1,
			IndexInYear = Convert.ToInt32(json.indexInYear) ?? 1,
			JournalCode = Convert.ToString(json.journalCode) ?? "",
			Name = Convert.ToString(json.name) ?? "",
			OriginalCurrency = Convert.ToString(json.originalCurrency) ?? RegionInfo.CurrentRegion.ISOCurrencySymbol,
			PaymentDate = Convert.ToDateTime(json.paymentDate) ?? DateTime.MinValue,
			Type = Convert.ToEnum<BankJournalEntryType>(json.type) ?? BankJournalEntryType.BANK,
		};
	}
}
